version: "3.9"

services:
  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    ports:
      - "8000:8000"
    volumes:
      - ./services/auth_service:/app
    environment:
      PYTHONPATH: /app  # ⬅️ Ajoute ceci !
      DATABASE_URL: postgresql://auth_user:auth_pass@auth-db:5432/auth_db
      JWT_SECRET_KEY: super-secret-key
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_MINUTES : 60 * 24 * 7
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
