[project]
name = "auth-service"
version = "0.1.0"
description = "The authentication service for the 2CommunityApp"
authors = [
    {name = "Kascabrel",email = "https://github.com/Kascabrel/fya_monorepo"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
